name: Test Install Instructions
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  install-check:
    runs-on: ubuntu-24.04
    steps:
      - name: Install
        run: |
          sudo apt update
          sudo apt install -y texlive-full
      - name: Checkout
        uses: actions/checkout@master
      - name: Test Installation
        run: pdflatex tests/test.tex
 
